### ISSUE TITLE
只有词库没有词频

### ISSUE THREAD

**Issue by zcwfeng** [pureexe/thai-wordlist#1]
只有词库没有词频

**Comment by pureexe** [comment]
@zcwfeng I can't read Chinese. Could you use English please?

**Comment by zcwfeng** [comment]
Only word library, but no word frequency. Can you add the word frequency together

**Comment by pureexe** [comment]
I won't add word frequency to this repository.
but if you want Thai word list  with frequency, it had available at http://www.arts.chula.ac.th/~ling/TNC/contents/File/TNC2_freq-5000.xls by  
[Thai National Corpus](http://www.arts.chula.ac.th/~ling/TNCII/)

And we also have alternative version of corpus available at https://www.nectec.or.th/corpus by [National Electronics and Computer technology center: NECTECT](https://www.nectec.or.th)
